# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10409da1fa9afa10f189d86f6973e25a84f4c253d38bd14501c36bde2fb0cb6ad2faf1ad58321e04c818ef0e5abe5317f40592e64807b11fbe9e633f070eab76

test:
  secret_key_base: cb39962ca7fa6e8c1545e6e0372c5a4959d9cf12c7734246d6b2867e0162be0554f56bc3fd7487de265be8daa252a68dcec8d0bad0dfa0cd8192372705ba7139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
